feat: add browsers flag
storybookjs/test-runner pull request #55
Opened 2022-02-16 16:09 UTC by yannbf

This adds the possibility to set browsers via CLI such as:

```
yarn test-storybook --browsers webkit firefox
```

2022-02-17 09:50 UTC, shilman commented on src/config/jest-playwright.ts
> +        browsers: TEST_BROWSERS.split(';'),
Comma-separated and `trim()` each component?

2022-02-17 09:51 UTC, shilman requested changes

2022-02-17 09:51 UTC, shilman commented on src/config/jest-playwright.ts
> +        browsers: TEST_BROWSERS.split(';'),
Comma-separated and `trim()` each component?

2022-02-17 09:51 UTC, shilman commented on src/util/getParsedCliOptions.ts
> +      'Define browsers to run tests in. Could be one or multiple of: chromium, firefox, webkit'
```suggestion
      'Define browsers to run tests in. Could be one or multiple of: chromium, firefox, webkit (comma-separated)'
```

2022-02-17 17:00 UTC, shilman requested changes

2022-02-17 17:00 UTC, shilman commented on src/config/jest-playwright.ts
> +          .filter(Boolean)
@yannbf re-order these

2022-02-18 11:31 UTC, yannbf commented on src/config/jest-playwright.ts
> +          .filter(Boolean)
Done!

2022-02-18 11:45 UTC, merged